### ISSUE TITLE
Build error - Could not resolve com.alibaba:arouter-api:1.3.1.

### ISSUE THREAD

**Issue by gongzelong0718** [renxuelong/ComponentDemo#1]
> Unsolved dependencies: (20 errors)
> /Users/gongzelong/Android/Modularization/ComponentDemo |  
> app/build.gradle |  
> Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.alibaba:arouter-api:1.3.1. |  
> Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve com.alibaba:arouter-api:1.3.1. |  
> Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve com.alibaba:arouter-api:1.3.1. |  
> Unable to resolve dependency for ':app@release/compileClasspath': Could not resolve com.alibaba:arouter-api:1.3.1. |  
> Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Could not resolve com.alibaba:arouter-api:1.3.1. |  
> base/build.gradle |  
> login/build.gradle |  
> share/build.gradle |

**Comment by renxuelong** [comment]
Seems to be a problem with the build.gradle file configuration，Can you upload your build.gradle file?
