### ISSUE TITLE
极光推送集成

### ISSUE THREAD

**Issue by ZhuRg** [renxuelong/ComponentDemo#2]
你好，关于集成极光时有些问题想请教一下。
Q1：极光推送应该不能集成在base_module中吧？怎么才能做到集成调试或者单独调试都能收到推送啊？不能申请多个包名对应的appKey然后每个moudle中声明一遍吧？~~期待你的回复，thx.

**Comment by renxuelong** [comment]
推送这个功能，一般是单独创建一个 PushModule 来处理，在收到推送时如果需要与其他组件进行交互则通过 componentbase 组件进行通信。

如果需要单独调试单个 module 中的功能，可以使用主 Module 也就是 App 只添加推送和需要调试的 module 这样也不会影响编译速度，同时，也只需要以 APP 包名申请一个 appKey 即可。具体单独依赖的逻辑可以查看文章中的第六点 - 组件集成调试 部分。
