### ISSUE TITLE
好像组件跳转回退时有些问题

### ISSUE THREAD

**Issue by Joehaivo** [renxuelong/ComponentDemo#4]
是把每次跳转都加入了回退栈吗

**Comment by renxuelong** [comment]
> 是把每次跳转都加入了回退栈吗

能详细描述一下你遇到的问题吗？

**Comment by renxuelong** [comment]
能详细描述一下你存在的问题吗

**Comment by Joehaivo** [comment]
比如，依次点击去分享-去登录-去分享-去登录.....多次点击，回退时会原路依次返回，这里感觉很奇怪

**Comment by renxuelong** [comment]
这个是由 Activity 的启动模式导致的，使用 ARouter 实现的 Activity 跳转最终是调用了原生的 startActivity 方法，所以启动的 Activity 会被系统的回退栈管理，跟组件化是没什么关系的。

如果想解决这个问题，可以将 Activity 的启动模式设置为 singleTask 或者 singleInstance
