### ISSUE TITLE
并没有真正解决组件单独运行的问题啊

### ISSUE THREAD

**Issue by cjztool** [renxuelong/ComponentDemo#5]
比如登录组件，即便有componentBase，单独运行登录组件，配置上并没有添加依赖到分享组件，界面里点击去分享组件必然逻辑不正确。

**Comment by xiaojinzi123** [comment]
> 比如登录组件，即便有componentBase，单独运行登录组件，配置上并没有添加依赖到分享组件，界面里点击去分享组件必然逻辑不正确。

其实单独运行这件事可以新建一个单独的 `Module` 去包含需要单独运行的 `module` 运行.这种方式除了 `Module` 会比较多之外,其他一点坏处都没有,而且还贴近原生

**Comment by renxuelong** [comment]
> 比如登录组件，即便有componentBase，单独运行登录组件，配置上并没有添加依赖到分享组件，界面里点击去分享组件必然逻辑不正确。

组件化可以解决的是单一模块单独运行调试的问题，如果设计多个模块联调 App 中要同时引用两个模块，不能只引用一个模块你就要实现两个模块的功能
