### ISSUE TITLE
多个fragment

### ISSUE THREAD

**Issue by shuiming11** [renxuelong/ComponentDemo#6]
想请教一下，如果在主页需要切换多个模块的fragment,那不就要写多个fragmentActivity了？

**Comment by renxuelong** [comment]
不需要的，文章中介绍了主项目不直接访问组件中具体类的情况下，如何获取组件中 Fragment 的实例并将组件中的 Fragment 实例添加到主项目的界面中。可以看项目的文章介绍  https://github.com/renxuelong/ComponentDemo
