### ISSUE TITLE
单独编译share模块会报错，请问是怎么解决的呢？

### ISSUE THREAD

**Issue by sanyusily** [renxuelong/ComponentDemo#8]
Unable to find a matching variant of project :share:
  - Variant 'debugApiElements' capability ComponentDemo-master:share:unspecified:
      - Incompatible attributes:
          - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found incompatible value 'Apk'.
          - Required org.gradle.usage 'java-runtime' and found incompatible value 'java-api'.
      - Other attributes:
          - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found compatible value 'debug'.
          - Found com.android.build.api.attributes.VariantAttr 'debug' but wasn't required.

**Comment by renxuelong** [comment]
可以提供更多的信息吗，比如编译使用的 gradle 版本等信息；还有单独编译 share 模块是指单独编译这个 module 吗？

**Comment by renxuelong** [comment]
有遇到相似问题的可以继续提 issue，这个没人反馈就先关闭了
